version: '1'
name: 'Listener Site'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_LOG_VOL}:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - net
    volumes:
      - ${SOURCE_VOL}:${SOURCE_DIR}
      - ${BACKEND_LOG_VOL}:${LOG_DIR}
    environment:
      LOG : ${LOG_DIR}
      SOURCE : ${SOURCE_DIR}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - net

networks:
  net:
    driver: bridge
